# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: 1a317aed-2ae0-467e-a97d-46ea4e51f919
  resourceGroup:  rg-sucharita
  storageAccount: terraformtfstateskip2
  container: terraformtfstate
  tfstateFile: terraform.tfstate
  anyTfChanges: false

steps:

- task: TerraformInstaller@0
  displayName: install Terraform v0.12.28
  inputs:
    terraformVersion: '0.12.28'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Microsoft Azure (imcloudoperations): #1265675(1)(1a317aed-2ae0-467e-a97d-46ea4e51f919)'
    backendAzureRmSubscriptionId: '1a317aed-2ae0-467e-a97d-46ea4e51f919'
    backendAzureRmResourceGroupName: 'rg-sucharita'
    backendAzureRmStorageAccountName: 'terraformtfstateskip2'
    backendAzureRmContainerName: 'terraformtfstate'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Microsoft Azure (imcloudoperations): #1265675(2)(1a317aed-2ae0-467e-a97d-46ea4e51f919)'
    providerAzureRmSubscriptionId: '1a317aed-2ae0-467e-a97d-46ea4e51f919'
    allowTelemetryCollection: true

- task: PowerShell@2
  displayName: detect any terraform change
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    targetType: 'inline'
    script: |
      # Write-Host "LASTEXITCODE : $LASTEXITCODE"
      $plan = $(terraform show -json tfplan | ConvertFrom-Json)
      $actions = $plan.resource_changes.change.actions
      Write-Host "Terraform actions : $actions"
      if (($actions -contains 'create') -or ($actions -contains 'delete') -or ($actions -contains 'update'))
      {
        Write-Host "Terraform will perform the following actions : $actions"
        Write-Host "##vso[task.setvariable variable=anyTfChanges;]true"
      }
      else
      {
        Write-Host "There is no change detected in Terraform tfplan file"
      }
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Microsoft Azure (imcloudoperations): #1265675(1)(1a317aed-2ae0-467e-a97d-46ea4e51f919)'
    providerAzureRmSubscriptionId: '1a317aed-2ae0-467e-a97d-46ea4e51f919'
    allowTelemetryCollection: true
